### ISSUE TITLE
Major Bug

### ISSUE THREAD

**Issue by D0us** [rileymccullagh/disconnect#1]
![pigeony](https://cloud.githubusercontent.com/assets/6095869/24336654/d7f1f638-12de-11e7-9155-97385135cb12.jpg)

**Comment by rileymccullagh** [comment]
Major BIRB

**Comment by rileymccullagh** [comment]
fixed
77$ZZIZOI7Z$I$OOZ$++7OO8ZO$Z8$ZZI$$ZZZ$$IIOZ$$I7$?777IIIZ$OZO$$$$7Z$IZ?Z7II?+??I?I$7$I7Z7Z$$$+$7?7$$ZZ7777$ZZZ7$7$Z7?$$=I777O??I++7$7?~I$?I+
II7Z??$I$+I$77O7$IZII7ZOZZ$OZ88$OOZZZ?ZO8I7I7$?=?$ZI7?77I77I$I7+$7Z7$Z+7Z7II+II+?7I$8Z77$Z777$Z7?$$+?8IZZ7Z$7I77$$=7Z$O=$$?$=+I77$$$$?+II+?I
IZ?$77~+I?$=I7ZI7?I?$$7O8$$Z7$7I$7$OZO88IZZ$?$$IO?7=+?77$7Z$77ZIIIZ$$$=$ZI77II=+???77$?77$$$$7$$$ZZ~I7?+$$7IZ$7?$+?II+777~+I~I+I?=???II??+O$
$OIZI7=??+7?I777+7+Z$II$7IZ$777$O7ZZZ8OOZ77$ZZI7II7777I$?+7$$$O$7$$Z?O~7?Z+7~77?$7Z7I$7$Z$$$$Z7Z$O77ZZ$?IZ$I?$$7I$7Z7$I7?++7I77$7$$$77I7++?7
Z$$+I777?$I++7??IO?777?$7O$ZI77OZOZZ:=?IZ?OIZZOI+OI7$Z7+$7Z7Z$7Z$$$$ZI~?I??$I7?7+?7Z$?+7IZO7?$~?7$ZI$ZOI??ZI$?+$I7$$7ZIZI77Z?Z+$ZZ$Z?I7I7??I
??77=+I???7?+7+7=I+II8$II$?I7ZIIZ$$78ZZIO+=I7OZ7II$77OI$Z$$IZ7$$$7Z$7$+++?I?7$7+I=+7ZOZ$7?$7ZZO7IZZ?$ZOZ7$$$Z$7++I?I$777I$I$?Z+OI$Z77?$II7ZI
?7$$$=$Z+~I7++?II+?=+77Z7I?IZI$$$77=8$IZ7?$?$$$Z+I7II+?$O$$O8=$7$=I$$$?$$$+I$I7$77I++I?+?$OIZO$77$O7+Z7D+ZZ$+?ZZI$?IZZ?7IZ7$$I+$~7$+IO$II7?+
7$ZZ7??Z7==7?+I??+=ZI?I=7IZ=77777I$:O$$OZ+$IZ7$?77II77?+Z$$7IZ?Z7Z7Z7+?IZ$+77I7$~?~?II++$Z$=~=$8O$O$$$?I7$8Z+?==$I+II7777$7$$II+?$I7O$$77$$I
$ZZ$??I$7I7$++7?=?=+:Z??Z?+$77II$$Z??7Z$$I+?$I7?7$$Z7II$Z7OI$IZ77$$$=II?~$I7$I=+++=+~?I??I++$$ZZ777Z?7$$$II??7?$$:I$I?I??=?+~?~=+=IZZ?I7II77
I=~III7$???+??7++??7=7I?+7I$7$$I$$$$I??$$ZI?III7=I?Z7O8I?$7+I$Z$$$I7$Z$7I$I?$ZI~+?==II?==77=8IZI7Z?Z?$+7Z=Z++~Z?IZI=I+IIZ7I$7$Z$I+7~IZ7+=??$
$7$~?$Z77?7??+=$I?+7+Z7I?77Z7Z$?$+7$$Z7777I?I?7?$~=?I?Z?7M7+???Z8?$Z=Z$$OZ$$77$II777=~+=~I???+7Z?$+???OIDO$OI$~7??~+:Z=I7O$77I:$?$7$???$$77+
~?7Z?~$I$7$I???+ZI=7I7+II$7ZI$I777IIOI77?7$$+$?=7$IZ$7I7+I~ZDN??7I7$$IZ$?$IZ7Z$I?=~+==~=?~I7I$+$Z+?$$=I++7?7?~I$?++77II777+I+=I=I+7++II=ZI7I
$O$I$++77+II7?III7I7?+I$7$7?7$$Z+$$7?$Z$I?+7??777~I7I$77I+II=I?8OZIO?IO$7++7$O7$$7:$+?7O=III?++OI+IZ$??+7?$~?I~$???I7???7Z7I+II??=7=++=+=+7$
$7I7I$??I$$?77?77$$$777I7+?I$$?$I7$I$Z,$7O7$Z$7$I77$$III?~+OZ7DIO$$Z7?7ID?~$$O+7O=?~+Z~:::::==?II?$+=I=?7I=I7?I+I?7$7?+?II??77+7?$,77+?,=IIO
$II??III=+??+$?I7?7?II?7Z$$$$Z$ZZ777??$$=$Z$7IO7$$:$~7$+I=77$7?$IID?I$88O$=O+?+??+:~~~~:::::::~I=:=?+II+I??7?I$Z+$7I?I+I??7OZ=7I=++=77==:+$7
O7$$?IZ7?I7$I7I$Z$I?I+?=$7Z$7ZOZ7Z$$7I$O$IZ7IZ7$$Z$?7?I7?$77I?$???I$8$DD$+ZIZ8I+~~~==~~~~~~:::~:~,~?+~I?II?II7++I=7$II+?=??$7~?:7I?7I?I=7I~$
$7$Z7I$$$$$7=I?77II=?Z8I$$Z$I$$$8II7$Z$OOZ$$ZOI$$$?+$ZII?II?II$+IZIO7+7O?=$+?7==~~~=+?++===~=~~~~~I7???++:7I==77Z7I7$ZIIII:II=~I$7$~?=I+I$==
$I?+?$~$$Z?=7$77II$OI7?7IZ?$7$ZOOO7$Z7Z$$OIZ$$OZ+I=7$IZI78+7I7$Z88$7I:=$=??++=+=++=+?I?????++===+=I$I?I7$77~?$7Z$II?$~?Z7+7=$~ZIOI7Z?.?7+Z?~
7+I?I?++$Z77OIII+I+=I7$?II77Z$ZO$$OZ7ZZO+,$7ZZZZ7777777$+$?$$7$7Z7OI~:O+?=Z=?????????+?7I$7II????II$O7=I?7$7?7ZOI=+:I77$$$=$++IZOIZI7OII~=I:
7II$$OZ7I777++II7?7I++:~I$?7ZOO=O87OZ?ZO8?Z7$ZZ7ZZZIZI$Z?7$=87$I$$$,$7I?I~=??II?+++=++++NZI7777$7=,7Z77I$?Z+I$$I7I+I?I7O+=Z+?~Z7?OZO$OIZ+?O7
IIIZ7+?I7$$7$$7$$7I777II++OOOI$Z8Z$O$ZZI7ZOZ$ZZZ$=77I$ZO+?+~~:~+~~~::~ZD77777II?++++=+?===+++I$I+:,..IZ?$$OZ$~7OI?+:I=?8:88$$=O$$?ZZI$7$?8=I
7$II$Z8OZ$$7?IIII?I+$OZOOO$$I$=OZO$ZZ$$8O77III7=ZI++:===::,::::~~~=~~~~~~$$Z$77I?+======+?+=+??++?$Z$:,$7$O~OZO,77+DZ~+=Z8O$II+IZZ7ZIZ?$+ZO$
7?IZOZOZ7$$7IIII+++++,?DO8888OZDZ$+O8O~:Z88N?:~=~=++:,:~:=~====~~~~~~~==7$ZZZZZZ77?+=+?++?+?+?+I?=IZI++=+=OZZZIZII~??$Z+?+$O$OO=IOOZ7+77++$Z
IZOOO8DZZ$$7II??+~+++=~+7?O88O888888OI?$O+==:II=:~:::~~:~~:~~~~~~~~~=+?+7$ZZZZZ$$$$7III7?+?I7$7$?=+7$$$$?Z7ZZIIZIDZ~~~7?7+?I$77O=OIOOZI$+Z7O
$ZZO8OOOODZ7I?+====++====~::~:::,:I,::,~~~=++I======~~~~~~~~=~=~~~==+?~..77II$$777$77I77$$$$I77Z$=ZIZOZ7=:I==7IZ8+$$I~+$~$$I7=+7OOZ$$ZZ++Z$7
Z=7Z$IZZOZZ$Z8++===+$7=:::::::,====:~~~==?++=+?+=+==~==~~~:~:~~~==+=+~....~,=~~I77IIIIIII77I?I+ZI+=?Z7?IO8DI7+=~~:=I7Z+:=I$Z$8?=IO?ZZO$I78OZ
?77Z7ZZZZ$$7$II$I====+?7$$$~~=======+=~==+???+++==+====~~~~~~~~:~====+,......,,:77$77III77II++II+77~?+77OOI=?7ZZO?7$:O~+:==$$8$=OZ+?OZ7OI$I~
$7Z7OZ7$ZZ$I??I??+++?7+====++??+=~==+=+~=+7?I?++++=+===~=~~~~~:~~====+,.........,,?I7IIIIIII?++$$$777$+I+$=Z7$8I=?+++=Z++:=7$?Z$?$Z?7O$Z+$$7
Z$$$$?ZZ$?+?I???????+==++++++++++?+?+++??++II?I+?+?+=+==~~~~~~:~~~~=+++~,,:=+:=~:::I7IIIIII?+++?$7+O7$Z7I=+~$OZ77+$N$7I$Z$IZZI7=I$O$~I.,.=Z$
O8O7I$OO8OON$=?I??+I7???+++++=+????????I++?7II??I+++~~====~~~~~~~===++=??,,,:..:,+I7777III??++++ZI$$Z7I$ZZ7$?++$887Z8OZO$=Z$7ZZD77O=7II$O7=:
ZZOOOZZ7+=?:IDDZ?I?ZO$+????I=?II??I?I??I?+?+IIII?+??++++?+==+===~=====++??I7I$77III77III???+++++?77IIDO$Z7I$Z77II+$I77$77$7Z$$7O$+OZ7+ID7Z7$
??IIODZ7$$$I?7$$Z7Z$$Z++????+?I?I??IIII7III?77I7IIIII?II?+++=+==:=++++++???II777I7IIIIIII??++++++I=?+I?7OI7$O7$$=7$Z7Z7Z$7$$O$$ZIO+Z87IIOO$O
ZZI?IIZ?Z$I7$$$7IZZ7$$?=?++?+?IIIIIIII7777I777777OI7ZZ7II77I=+==~=+++++???IIIIIIII7IIIII???++=+?+8$+OZ~?ZI$$O7==?=+IOZIOI$$7ZOZOI=IIZ$77IZO$
?7OOZ$Z77OI$$$77$$?ZZ$??7?+++IIIII77I?I7I77III$O8$OZ777$77I????==~=+??????IIIIIIIIIIIIIIIII?++?++Z77Z$O7777I+7I$$$$I+:+Z+?Z$77O==7O?$$I$ZZZZ
??+$I7$ZZI?+ZZ7Z$$+$$7$7+IIII7IIIII777777777777ZZZZ$$ZZ$777$7I??+==+++??IIIIIIIIIIIIIIIIIII????+?ZIZ7I7I7Z$+=+IOZ8I7+==I$$$IZI~7OZ$IZ$$+?$ZO
I?$?ZI7I7?$Z7$$Z$ZZD77$7II7?I777777777777777I7$$$Z$ZZZ$ZZ$$ZZ$$I?==++???IIIIIIIIIIIIIIII7$$??????$7ZZZZI+ZZ+?7ZO+Z7?7$O+$8ZZ$??777,I$87$$ZZO
$$$77Z~DOZIO8$I+$ZZZZO$Z?777$77$$7$77$$$$77777$$$ZZZZZ$$ZZZ$$$$?==+++???IIIIIIIII77II777777I????Z$$Z7??==?7OII$8$+7O$8O7ZZO8ZIZZ$$Z8$O==IZI7
?I$$D7$OZ77ZOIO$D8:I7$ZOOIZ??II$$$7$$$$Z$7$$$7$$$$ZZZZZZZZOZ$ZZ?+++++++?IIIII7IIIIIII7$77777II7$$ZZO$???+?7?I77+IZZZ$7O~$Z$ZZ7$7$O8OD7Z77=8+
$$I?IOZZ7OZ=Z8O8DZ8NI=?$$$Z7Z+?$$$$$$ZZZZ$ZZZ$7$$$ZZ$ZOOOOOZZOZ?++?+++??IIIIIIIIIIII77$$7777II7O$77?O7=Z$7Z8?O$$IIZ7O$Z?+?7OZ7OOID8$7Z$7O7I$
O77O77+$$I$OZZ7Z7$ONZO7~$=7O$7$$$ZZ$$ZZZZZZZ$Z$7$$ZZZ$ZOOOOOZOZI?????????IIIIIII7III7777$$$77IZ$I$7=7O$ZO7I?Z8?7O?77Z$OI78?IOIZ$IIIO8O8Z?III
Z,OO7Z7I$$$O$OO$ZZDDDMDZ+7I?$Z$$7OOZZOOZZOOZZZ$ZZZZZZZZZZOOZZOO$I?+??????III7IIIIII777777$77I7Z$Z?+ZOO+?7+Z7Z+=+I77I$Z777$ZOZ?$I$O?88OOZI???
D+:$OZ77?$Z$7OZ8$OD8O8ODDN7=7Z$7$ZOOOOOOOOZZZZZZZZZZZZZZ$$ZOOOOZ7IIIIIIII7II777I7777I77777IIZ$I+$+I?7=+~+7+I=+DZ8D$?7$$ZZ?I?$IOONZOO$?7ZI7NZ
O7Z:Z7Z$$Z$D?.$88Z8888MO888NN7IOZD8D888OOOOOO8OOOO$ZZZZZZZZOOOOZZI??IIIII77II777III7IIIIIIII7$Z$Z7$$7=I7?I$?$~ZZ+8++ZI$$7I=ZION7D:?==:$+$O=8
,=?O8I$OZ$IOOIZ$$OZ8OOO~7$+$Z8Z8OZ8N8D88O888O8O8OZZZOOOOOZZZZOOZI??I77777II77I7IIIIIIIII???$8O?ZO$7?IZ??+OIZ?+?7III7?II$I?III8$7??O7I?II7$7Z
III7Z7?+77II8IZIZI7OZI$8==ODZ?I78DN88DD8888888888OOOOOOOOOZZZ?7$7+?$$77777III7IIIIII?I????O$$Z$7+Z$$$7I$77??I+ID7Z$II$$??$$7I7?+IZ?$Z8NI::7Z
7??I?7?:7I=+$Z7$Z$+7$Z8OI7Z$O77O8ONMO7$OOD8888888888888888O8O$II77$$$7777IIIIIIIIII?II???$$8D888Z7OZ$7~7?I++$Z+7Z$O7$7$~$IO?$I$=++$I=87++Z$D
++?7I+7?II?~+?+$7$II7$Z$$77$$7$$7ZO$IIZO777$$ZO8888888OOOO$I$$$$$7$$77III77IIIII??????IIZODD87ZO88$Z7?+?+I7$Z$+$8O+?I7$=$I7=$$7+?IZ+Z?:Z$OI+
I??:7?$$?+=I7$++$+?IZOO8II7$$7ZOO7IO8O$77??++777ZOO8DOO8ZOOOZZZZOZZ$$$$$777II?III?I?IIZNO8D88$~8OO$O7$=I77+N7?$8ZIII$777++?Z=II,=+?I=7I8$7$?
7I++~7?7?=+7OO+$$$$I??++???7Z7ZOZO$ZONM7Z=~I+++?I7IZ?ZZOZOOZOOOOZOOZZ$$$77777II7I+7II8O8$ZNOO$7I$ZZI?I+IZ?I8$+O$7?7$:I$?I++???Z~I+=$$I?77$I$
I7??I+$?I+7+I?7I7ZZIII$888Z$Z?8ZO7OZZ+IOIO?=?+??I77$?$IZOOO88888=OOZZ$$$$77$$$$$7777$DZDNDMDN7878O8+=I?7?7+I7II7I:=::?7I+??I?+:ZII?7III$I788
I???II+I?+7II?$$ZI$Z?+DD7$$O$IZ$ZZ$OIZZ7IO7I$IIIIII7?+$$O878D8OOIOZZZZZZZ$$$77II$$$$$8$OZZN8DO88$ZI=7I?7~$+$77++$??I=:I+II=?$I=+ZI:O7I$I$$7Z
7++I+7I~,+7$?7O7$7$II+$7Z+7?+O$I$Z$ZOOZOOOZ$7$I$I?=7I=OO$ZDDODNN8,OZOO8OZ$77=?7Z88$NN88O$I$7OD?ZZ7?I88?~$7I7?$$++I$7++:=II?~?7I7IZ~=$?$$77+?
7???+?77I?$???OO7$I+?=~Z==I+O$$Z7ZZ$Z7OOZO+$OI$7DZ7D8=7Z78O88O8ZNO$O8O7$$Z77Z8Z?$OZON8$Z877Z7$7ZZZO$$$I7=IZ++I?$II$I$7+=7I$?$Z$I++$$$7$+?7I+
77=?I+IIIII~++77+I7?I??.Z?O7Z7$$O$IOZI7$$Z=DZZI7II?77?I7788ODDNONO:I$ZO88Z$Z=M8O$7$I8I8$~I:,I$O7O8877$+I??O==?7I$+7I$$I+$I77I+Z7~7Z$7I$~I$=?
7$I7?7??:~?~+Z77?I7I?7??IIOI$?$?ZO$IIZ$$$$I8ZI77IZZ77??ZZ8D7DO$ZDZD+=$N$OOZOZ87?$Z$=7ZZ$~7ZI?IZIOO?N7?$???I$I=Z?+Z$$$$877I$$IZO7~7$777I+~?7$
I7II?++++?III==7777??7$I~+$O$$$7I7$O$OIO7$IIZZI77O$777O$O7Z8Z$?7?ZO~$$$IZ$ZZM$=$$77$I7$.Z87ZZ+++++7?IIII=O=Z?I=+$77$$$$+?$$Z7IO7$7ZZ$7II=?I$
$$Z+?$?+$7+7?~?+=I=++7ZII7?7$OZI$$7IOZOO$?$77Z$Z$$I7OZI$$II$7$87$OI7+$$Z$$ZZ$?I$=+$ZI$I7$ZOI77I+?777I+7?II?O?I+7777Z77$77I7ZZ$Z$?7Z?7I7?$?I$
$$$I?7I+=O=I+?+?+~+=+O?IOI$$7$$7$7I$Z$ZOOI?7??ZI$$IZZII7I+$7$Z8Z$$?7+ZI$$ZOO+Z7I77IZ$$?O787I7I$Z77$I+?I7$?7I$$7?ZI7Z$7Z$ZZZZ$?7?=7Z77$I=7?I?
77?O++777+??I=I$?I?++Z$I7$7=77IZ+$$O7ZOI77$$??$$$7IZ777ID7?I+$IIZ7+IZ=$?~$$+$I$8$ZO$?+$$$O$Z7Z7ZO7$??7II77?II7??+$7Z7Z7I$Z$ZZ?OZOZ+$?~$??I?7
O$7$I77I+?=~??77+II+II777III+~+I8?$$I?Z$$8+7?I?7?~77$$O=?$$?=~??IZ???+?$?$7I+$Z7$?ZII$?+7,+~?77Z777=+I+7IZ7$ZII7$O$ZZZ7Z$$OZ$I7Z$OZ7I?Z?IZ7$
8?$7I7?I??+?II7ZI7?I?=+$++=777$7I7$I?+++?+$+7Z$I$IZZZ$$+ZI7+I7?$$OI77???$$?+IO?7O$I+77$OI?Z7$+7=O?$+=I?++I+ZZII$$7Z?OZ7$O87$ZZ$Z$$Z$ZI$$7I7$
77+OZ$$+7+?++77?=~+?O?777$?+?+$?I=$Z$7?7I?I7I7$77Z7?$IIII$7IIZ7ZI$Z$O$~II$$7$+ZII7I+7?77ZI?I$$77?OI==7I~?IZ7?ZOZIIOIZ7$OIOO$OZ$ZZZ$$+Z7Z77$7
?I7I7$O+III=+77+==++7+I7I?III+I$77$$I7??==?I77I$$7?~?I7ZZI7777$$$7$ZZ$?=$Z$?$I+I$$Z$I7I+$$=7?77$777+=??+$IIIII?I$Z7$77ZOZZ87ZZ$$Z$$7ZZZ7$$$?
777OI?7+$$Z7~?7I++=?+I+I=?+7Z~?IZ$77O$+I7I7?I77Z$$Z$I?II7$ZZI7$Z$$O?$ZZ?$?IZI:+=I$?7?II7?7I7?$7O$?IO++?=?I$$$7$7Z+O777D$?=7$7ZZ$O$OZZZ7$7$$Z
7$++?IZZ?$ZI?$77$7?II?I?II~$I7I77$7777$III777ZZ$77ZZI$Z?$$I$$IZO$$Z$Z$$+7$$$$$O$ZZOI+ZIZ77+$$7I$7?+I77$77ZOZOIZ$I+$7=Z$Z$ZO$ZZI?$?II=~I+II7I
$$7O7=7IIZ7?=$7$$7I$II77$7Z777II$$7Z$ZI7I7Z$$Z$$$7?77O$$Z$7I$7I7Z$OOIZI$7$Z$7$OIOZZ??$Z?O++??777?7I$I7Z$II+778OZO$?$7+$OZZO$IO77II$77?7==?Z$
7$II7OI?7$7$$7IIZ$$$I+7OZI$$7I7?$$7$$$I87IO7$ZZ$7$I7I7I$$IZO$I777Z7Z$$7ZZ$?D$7$+OZ7++:77II?$I7I7I7+ZI$I77?ZO7I77Z7Z$7$~Z8O$Z7$IO$7$I$7IIZ~??
